[2023-08-15 20:11:31,918] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-06-05T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2023-08-15 20:11:31,919] {local_task_job.py:101} INFO - Task is not able to be run
