[2023-08-15 20:11:14,395] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-08-15 20:11:14,400] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-08-15 20:11:14,400] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:11:14,400] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:11:14,401] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:11:14,424] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-05-08 00:00:00+00:00
[2023-08-15 20:11:14,427] {standard_task_runner.py:52} INFO - Started process 47854 to run task
[2023-08-15 20:11:14,433] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-05-08T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpo8r4wk20', '--error-file', '/tmp/tmp9dtkpl0l']
[2023-08-15 20:11:14,433] {standard_task_runner.py:80} INFO - Job 119: Subtask extrai_dados
[2023-08-15 20:11:14,486] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:11:14,560] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-05-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-08T00:00:00+00:00
[2023-08-15 20:11:14,764] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:11:14,773] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230508T000000, start_date=20230815T201114, end_date=20230815T201114
[2023-08-15 20:11:14,805] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:11:14,823] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:30:05,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-08-15 20:30:05,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-08-15 20:30:05,986] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:30:05,986] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:30:05,986] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:30:06,008] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-05-08 00:00:00+00:00
[2023-08-15 20:30:06,011] {standard_task_runner.py:52} INFO - Started process 52372 to run task
[2023-08-15 20:30:06,017] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-05-08T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpv72qhize', '--error-file', '/tmp/tmp_qourq4r']
[2023-08-15 20:30:06,017] {standard_task_runner.py:80} INFO - Job 192: Subtask extrai_dados
[2023-08-15 20:30:06,072] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:30:06,141] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-05-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-08T00:00:00+00:00
[2023-08-15 20:30:06,399] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:30:06,406] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230508T000000, start_date=20230815T203005, end_date=20230815T203006
[2023-08-15 20:30:06,430] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:30:06,446] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:44:35,485] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-08-15 20:44:35,491] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2023-08-15 20:44:35,491] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:35,491] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:44:35,492] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:35,520] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-05-08 00:00:00+00:00
[2023-08-15 20:44:35,523] {standard_task_runner.py:52} INFO - Started process 57464 to run task
[2023-08-15 20:44:35,529] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-05-08T00:00:00+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpb091j524', '--error-file', '/tmp/tmphwim08do']
[2023-08-15 20:44:35,530] {standard_task_runner.py:80} INFO - Job 292: Subtask extrai_dados
[2023-08-15 20:44:35,586] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-08T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:44:35,661] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-05-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-08T00:00:00+00:00
[2023-08-15 20:44:35,766] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:44:35,773] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230508T000000, start_date=20230815T204435, end_date=20230815T204435
[2023-08-15 20:44:35,822] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:44:35,841] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
