[2023-08-15 20:27:37,208] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-08-15 20:27:37,213] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-08-15 20:27:37,213] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:27:37,213] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:27:37,213] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:27:37,235] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-01-09 00:00:00+00:00
[2023-08-15 20:27:37,238] {standard_task_runner.py:52} INFO - Started process 50750 to run task
[2023-08-15 20:27:37,243] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-01-09T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmp5wm0ftj9', '--error-file', '/tmp/tmpyt12bhav']
[2023-08-15 20:27:37,243] {standard_task_runner.py:80} INFO - Job 138: Subtask extrai_dados
[2023-08-15 20:27:37,294] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-09T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:27:37,366] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-09T00:00:00+00:00
[2023-08-15 20:27:37,595] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:27:37,602] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230109T000000, start_date=20230815T202737, end_date=20230815T202737
[2023-08-15 20:27:37,655] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:27:37,672] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:39:21,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-08-15 20:39:21,279] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-08-15 20:39:21,279] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:39:21,279] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:39:21,279] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:39:21,303] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-01-09 00:00:00+00:00
[2023-08-15 20:39:21,306] {standard_task_runner.py:52} INFO - Started process 55770 to run task
[2023-08-15 20:39:21,312] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-01-09T00:00:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpinnukk2q', '--error-file', '/tmp/tmpln5v0gji']
[2023-08-15 20:39:21,313] {standard_task_runner.py:80} INFO - Job 239: Subtask extrai_dados
[2023-08-15 20:39:21,372] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-09T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:39:21,449] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-09T00:00:00+00:00
[2023-08-15 20:39:21,646] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:39:21,653] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230109T000000, start_date=20230815T203921, end_date=20230815T203921
[2023-08-15 20:39:21,685] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:39:21,703] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
