[2023-08-15 20:27:41,079] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2023-08-15 20:27:41,083] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2023-08-15 20:27:41,084] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:27:41,084] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:27:41,084] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:27:41,105] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-01-16 00:00:00+00:00
[2023-08-15 20:27:41,108] {standard_task_runner.py:52} INFO - Started process 50789 to run task
[2023-08-15 20:27:41,113] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-01-16T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpw5h6tvk9', '--error-file', '/tmp/tmpiaz_pevg']
[2023-08-15 20:27:41,113] {standard_task_runner.py:80} INFO - Job 140: Subtask extrai_dados
[2023-08-15 20:27:41,163] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-16T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:27:41,234] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-16T00:00:00+00:00
[2023-08-15 20:27:41,420] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:27:41,426] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230116T000000, start_date=20230815T202741, end_date=20230815T202741
[2023-08-15 20:27:41,485] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:27:41,504] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:39:25,675] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2023-08-15 20:39:25,683] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2023-08-15 20:39:25,683] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:39:25,683] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:39:25,683] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:39:25,708] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-01-16 00:00:00+00:00
[2023-08-15 20:39:25,712] {standard_task_runner.py:52} INFO - Started process 55832 to run task
[2023-08-15 20:39:25,717] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-01-16T00:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpbh9v4j2j', '--error-file', '/tmp/tmpu0fizdw0']
[2023-08-15 20:39:25,718] {standard_task_runner.py:80} INFO - Job 241: Subtask extrai_dados
[2023-08-15 20:39:25,776] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-16T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:39:25,856] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-16T00:00:00+00:00
[2023-08-15 20:39:26,023] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:39:26,030] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230116T000000, start_date=20230815T203925, end_date=20230815T203926
[2023-08-15 20:39:26,090] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:39:26,110] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
