[2023-08-15 20:29:28,655] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-08-15 20:29:28,661] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-08-15 20:29:28,661] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:28,661] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:29:28,661] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:28,684] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-03-27 00:00:00+00:00
[2023-08-15 20:29:28,687] {standard_task_runner.py:52} INFO - Started process 51902 to run task
[2023-08-15 20:29:28,692] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-03-27T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmph0r2pt_0', '--error-file', '/tmp/tmpgim273ph']
[2023-08-15 20:29:28,693] {standard_task_runner.py:80} INFO - Job 174: Subtask extrai_dados
[2023-08-15 20:29:28,745] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-27T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:29:28,816] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T00:00:00+00:00
[2023-08-15 20:29:28,922] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:29:28,929] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230327T000000, start_date=20230815T202928, end_date=20230815T202928
[2023-08-15 20:29:28,984] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:29:29,003] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:43:55,745] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-08-15 20:43:55,750] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-08-15 20:43:55,750] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:43:55,751] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:43:55,751] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:43:55,781] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-03-27 00:00:00+00:00
[2023-08-15 20:43:55,784] {standard_task_runner.py:52} INFO - Started process 56972 to run task
[2023-08-15 20:43:55,789] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-03-27T00:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpy52ipw56', '--error-file', '/tmp/tmpatr_v_5a']
[2023-08-15 20:43:55,790] {standard_task_runner.py:80} INFO - Job 274: Subtask extrai_dados
[2023-08-15 20:43:55,852] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-27T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:43:55,927] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T00:00:00+00:00
[2023-08-15 20:43:56,032] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:43:56,040] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230327T000000, start_date=20230815T204355, end_date=20230815T204356
[2023-08-15 20:43:56,082] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:43:56,099] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
