[2023-08-15 20:16:08,328] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [queued]>
[2023-08-15 20:16:08,333] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [queued]>
[2023-08-15 20:16:08,333] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:16:08,333] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:16:08,333] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:16:08,364] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-07-31 00:00:00+00:00
[2023-08-15 20:16:08,367] {standard_task_runner.py:52} INFO - Started process 49107 to run task
[2023-08-15 20:16:08,372] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-07-31T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpigbjxqjc', '--error-file', '/tmp/tmpxelksv2q']
[2023-08-15 20:16:08,373] {standard_task_runner.py:80} INFO - Job 159: Subtask extrai_dados
[2023-08-15 20:16:08,436] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:16:08,512] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-07-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-31T00:00:00+00:00
[2023-08-15 20:16:08,575] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:16:08,581] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230731T000000, start_date=20230815T201608, end_date=20230815T201608
[2023-08-15 20:16:08,624] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:16:08,642] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:32:25,422] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [queued]>
[2023-08-15 20:32:25,428] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [queued]>
[2023-08-15 20:32:25,428] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:32:25,428] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:32:25,428] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:32:25,512] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-07-31 00:00:00+00:00
[2023-08-15 20:32:25,516] {standard_task_runner.py:52} INFO - Started process 54039 to run task
[2023-08-15 20:32:25,526] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-07-31T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmp76xh1kq9', '--error-file', '/tmp/tmpf97zh8o6']
[2023-08-15 20:32:25,527] {standard_task_runner.py:80} INFO - Job 228: Subtask extrai_dados
[2023-08-15 20:32:25,626] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:32:25,828] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-07-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-31T00:00:00+00:00
[2023-08-15 20:32:25,905] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:32:25,912] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230731T000000, start_date=20230815T203225, end_date=20230815T203225
[2023-08-15 20:32:26,061] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:32:26,080] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:45:54,421] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [queued]>
[2023-08-15 20:45:54,427] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [queued]>
[2023-08-15 20:45:54,427] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:45:54,427] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:45:54,427] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:45:54,450] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-07-31 00:00:00+00:00
[2023-08-15 20:45:54,453] {standard_task_runner.py:52} INFO - Started process 58460 to run task
[2023-08-15 20:45:54,458] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-07-31T00:00:00+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpm7nyz_4_', '--error-file', '/tmp/tmp7adkc5lt']
[2023-08-15 20:45:54,459] {standard_task_runner.py:80} INFO - Job 328: Subtask extrai_dados
[2023-08-15 20:45:54,518] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-07-31T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:45:54,606] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-07-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-31T00:00:00+00:00
[2023-08-15 20:45:54,682] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:45:54,688] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230731T000000, start_date=20230815T204554, end_date=20230815T204554
[2023-08-15 20:45:54,750] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:45:54,769] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
