[2023-08-15 20:27:31,415] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-08-15 20:27:31,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-08-15 20:27:31,420] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:27:31,420] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:27:31,421] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:27:31,443] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-01-02 00:00:00+00:00
[2023-08-15 20:27:31,447] {standard_task_runner.py:52} INFO - Started process 50686 to run task
[2023-08-15 20:27:31,451] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpq5w4lz_u', '--error-file', '/tmp/tmps0jisk6f']
[2023-08-15 20:27:31,452] {standard_task_runner.py:80} INFO - Job 135: Subtask extrai_dados
[2023-08-15 20:27:31,507] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-02T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:27:31,585] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-08-15 20:27:31,794] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:27:31,800] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230102T000000, start_date=20230815T202731, end_date=20230815T202731
[2023-08-15 20:27:31,864] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:27:31,882] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:39:14,453] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-08-15 20:39:14,459] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-08-15 20:39:14,459] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:39:14,459] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:39:14,460] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:39:14,486] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-01-02 00:00:00+00:00
[2023-08-15 20:39:14,490] {standard_task_runner.py:52} INFO - Started process 55650 to run task
[2023-08-15 20:39:14,495] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpvindpzy5', '--error-file', '/tmp/tmpbpjwpg6u']
[2023-08-15 20:39:14,496] {standard_task_runner.py:80} INFO - Job 236: Subtask extrai_dados
[2023-08-15 20:39:14,562] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-01-02T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:39:14,652] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-08-15 20:39:14,941] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:39:14,948] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230102T000000, start_date=20230815T203914, end_date=20230815T203914
[2023-08-15 20:39:14,989] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:39:15,007] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
