[2023-08-15 20:29:47,340] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-08-15 20:29:47,346] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-08-15 20:29:47,346] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:47,346] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:29:47,346] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:47,367] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-04-17 00:00:00+00:00
[2023-08-15 20:29:47,371] {standard_task_runner.py:52} INFO - Started process 52149 to run task
[2023-08-15 20:29:47,375] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmp4d7rpiwg', '--error-file', '/tmp/tmpb0cm83v8']
[2023-08-15 20:29:47,376] {standard_task_runner.py:80} INFO - Job 183: Subtask extrai_dados
[2023-08-15 20:29:47,425] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-17T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:29:47,500] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-04-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-17T00:00:00+00:00
[2023-08-15 20:29:47,607] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:29:47,613] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230417T000000, start_date=20230815T202947, end_date=20230815T202947
[2023-08-15 20:29:47,667] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:29:47,685] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:44:15,700] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-08-15 20:44:15,705] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-08-15 20:44:15,705] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:15,705] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:44:15,705] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:15,728] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-04-17 00:00:00+00:00
[2023-08-15 20:44:15,732] {standard_task_runner.py:52} INFO - Started process 57216 to run task
[2023-08-15 20:44:15,737] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpr76haiw8', '--error-file', '/tmp/tmph24gwbnf']
[2023-08-15 20:44:15,738] {standard_task_runner.py:80} INFO - Job 283: Subtask extrai_dados
[2023-08-15 20:44:15,792] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-17T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:44:15,873] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-04-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-17T00:00:00+00:00
[2023-08-15 20:44:15,939] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:44:15,945] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230417T000000, start_date=20230815T204415, end_date=20230815T204415
[2023-08-15 20:44:15,990] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:44:16,010] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
