[2023-08-15 20:29:15,061] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2023-08-15 20:29:15,067] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2023-08-15 20:29:15,067] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:15,067] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:29:15,067] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:15,098] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-03-13 00:00:00+00:00
[2023-08-15 20:29:15,101] {standard_task_runner.py:52} INFO - Started process 51717 to run task
[2023-08-15 20:29:15,106] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-03-13T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpikpbmkoh', '--error-file', '/tmp/tmpl1diojf7']
[2023-08-15 20:29:15,107] {standard_task_runner.py:80} INFO - Job 168: Subtask extrai_dados
[2023-08-15 20:29:15,164] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-13T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:29:15,236] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:00+00:00
[2023-08-15 20:29:15,388] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:29:15,395] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230313T000000, start_date=20230815T202915, end_date=20230815T202915
[2023-08-15 20:29:15,439] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:29:15,454] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:43:41,962] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2023-08-15 20:43:41,967] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2023-08-15 20:43:41,968] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:43:41,968] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:43:41,968] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:43:41,990] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-03-13 00:00:00+00:00
[2023-08-15 20:43:41,994] {standard_task_runner.py:52} INFO - Started process 56790 to run task
[2023-08-15 20:43:41,999] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-03-13T00:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpcucdfab9', '--error-file', '/tmp/tmp7rz37809']
[2023-08-15 20:43:42,000] {standard_task_runner.py:80} INFO - Job 268: Subtask extrai_dados
[2023-08-15 20:43:42,056] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-13T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:43:42,128] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:00+00:00
[2023-08-15 20:43:42,234] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:43:42,240] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230313T000000, start_date=20230815T204341, end_date=20230815T204342
[2023-08-15 20:43:42,291] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:43:42,318] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
