[2023-08-15 20:29:52,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-08-15 20:29:52,993] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-08-15 20:29:52,993] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:52,993] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:29:52,993] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:53,015] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-04-24 00:00:00+00:00
[2023-08-15 20:29:53,018] {standard_task_runner.py:52} INFO - Started process 52215 to run task
[2023-08-15 20:29:53,022] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpmcq_u7tj', '--error-file', '/tmp/tmpxe9j2u7l']
[2023-08-15 20:29:53,023] {standard_task_runner.py:80} INFO - Job 186: Subtask extrai_dados
[2023-08-15 20:29:53,077] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-24T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:29:53,146] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-04-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-24T00:00:00+00:00
[2023-08-15 20:29:53,245] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:29:53,251] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230424T000000, start_date=20230815T202952, end_date=20230815T202953
[2023-08-15 20:29:53,314] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:29:53,331] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:44:21,752] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-08-15 20:44:21,757] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-24T00:00:00+00:00 [queued]>
[2023-08-15 20:44:21,757] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:21,757] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:44:21,757] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:21,785] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-04-24 00:00:00+00:00
[2023-08-15 20:44:21,789] {standard_task_runner.py:52} INFO - Started process 57279 to run task
[2023-08-15 20:44:21,794] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-04-24T00:00:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmprk9cndbg', '--error-file', '/tmp/tmpjadyve66']
[2023-08-15 20:44:21,795] {standard_task_runner.py:80} INFO - Job 286: Subtask extrai_dados
[2023-08-15 20:44:21,849] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-04-24T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:44:21,930] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-04-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-24T00:00:00+00:00
[2023-08-15 20:44:22,004] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:44:22,011] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230424T000000, start_date=20230815T204421, end_date=20230815T204422
[2023-08-15 20:44:22,047] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:44:22,065] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
