[2023-08-15 20:29:09,000] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2023-08-15 20:29:09,005] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2023-08-15 20:29:09,005] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:09,005] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:29:09,005] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:29:09,035] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-03-06 00:00:00+00:00
[2023-08-15 20:29:09,038] {standard_task_runner.py:52} INFO - Started process 51651 to run task
[2023-08-15 20:29:09,043] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-03-06T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmphxesu7nc', '--error-file', '/tmp/tmpw57a8h9o']
[2023-08-15 20:29:09,043] {standard_task_runner.py:80} INFO - Job 165: Subtask extrai_dados
[2023-08-15 20:29:09,097] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-06T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:29:09,165] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-03-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-06T00:00:00+00:00
[2023-08-15 20:29:09,349] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:29:09,356] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230306T000000, start_date=20230815T202909, end_date=20230815T202909
[2023-08-15 20:29:09,536] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:29:09,554] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:43:35,753] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2023-08-15 20:43:35,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2023-08-15 20:43:35,759] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:43:35,759] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:43:35,759] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:43:35,781] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-03-06 00:00:00+00:00
[2023-08-15 20:43:35,785] {standard_task_runner.py:52} INFO - Started process 56725 to run task
[2023-08-15 20:43:35,791] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-03-06T00:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpidnyv98m', '--error-file', '/tmp/tmplgl51q3a']
[2023-08-15 20:43:35,791] {standard_task_runner.py:80} INFO - Job 265: Subtask extrai_dados
[2023-08-15 20:43:35,853] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-03-06T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:43:35,927] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-03-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-06T00:00:00+00:00
[2023-08-15 20:43:36,165] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:43:36,172] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230306T000000, start_date=20230815T204335, end_date=20230815T204336
[2023-08-15 20:43:36,204] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:43:36,221] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
